import { SubjectItem, PaperNode, PresetExamConfig } from './types';

export const EXAM_SUBJECTS: SubjectItem[] = [
  {
    key: 'bangla',
    name: 'বাংলা',
    nameEnglish: 'Bangla',
    category: 'general',
    iconType: 'bangla',
    color: '#DC2626',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-100',
    totalQuestions: 8100,
    solvedQuestions: 154,
  },
  {
    key: 'english',
    name: 'English',
    nameEnglish: 'English',
    category: 'general',
    iconType: 'english',
    color: '#4338CA',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-100',
    totalQuestions: 7500,
    solvedQuestions: 210,
  },
  {
    key: 'gk',
    name: 'সাধারণ জ্ঞান',
    nameEnglish: 'General Knowledge',
    category: 'general',
    iconType: 'gk',
    color: '#0284C7',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-100',
    totalQuestions: 6200,
    solvedQuestions: 98,
  },
  {
    key: 'statistics',
    name: 'পরিসংখ্যান',
    nameEnglish: 'Statistics',
    category: 'science',
    iconType: 'statistics',
    color: '#0D9488',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-100',
    totalQuestions: 3400,
    solvedQuestions: 45,
  },
  {
    key: 'physics',
    name: 'পদার্থবিজ্ঞান',
    nameEnglish: 'Physics',
    category: 'science',
    iconType: 'physics',
    color: '#16A34A',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-100',
    totalQuestions: 9500,
    solvedQuestions: 320,
  },
  {
    key: 'agriculture',
    name: 'কৃষিশিক্ষা',
    nameEnglish: 'Agriculture',
    category: 'science',
    iconType: 'agriculture',
    color: '#059669',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-100',
    totalQuestions: 4100,
    solvedQuestions: 30,
  },
  {
    key: 'chemistry',
    name: 'রসায়ন',
    nameEnglish: 'Chemistry',
    category: 'science',
    iconType: 'chemistry',
    color: '#EA580C',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-100',
    totalQuestions: 8900,
    solvedQuestions: 154,
  },
  {
    key: 'home_science',
    name: 'গার্হস্থ্য বিজ্ঞান',
    nameEnglish: 'Home Science',
    category: 'general',
    iconType: 'home_science',
    color: '#DB2777',
    bgColor: 'bg-pink-50',
    borderColor: 'border-pink-100',
    totalQuestions: 2800,
    solvedQuestions: 12,
  },
  {
    key: 'biology',
    name: 'জীববিজ্ঞান',
    nameEnglish: 'Biology',
    category: 'science',
    iconType: 'biology',
    color: '#059669',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-100',
    totalQuestions: 8200,
    solvedQuestions: 180,
  },
  {
    key: 'math',
    name: 'উচ্চতর গণিত',
    nameEnglish: 'Higher Math',
    category: 'science',
    iconType: 'math',
    color: '#D97706',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-100',
    totalQuestions: 9100,
    solvedQuestions: 240,
  },
  {
    key: 'psychology',
    name: 'মনোবিজ্ঞান',
    nameEnglish: 'Psychology',
    category: 'general',
    iconType: 'psychology',
    color: '#9333EA',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-100',
    totalQuestions: 3100,
    solvedQuestions: 55,
  },
  {
    key: 'ict',
    name: 'তথ্য ও যোগাযোগ প্রযুক্তি',
    nameEnglish: 'ICT',
    category: 'science',
    iconType: 'ict',
    color: '#C026D3',
    bgColor: 'bg-fuchsia-50',
    borderColor: 'border-fuchsia-100',
    totalQuestions: 5400,
    solvedQuestions: 140,
  },
  {
    key: 'mental_ability',
    name: 'মানসিক দক্ষতা',
    nameEnglish: 'Mental Ability',
    category: 'general',
    iconType: 'mental_ability',
    color: '#2563EB',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-100',
    totalQuestions: 4200,
    solvedQuestions: 80,
  },
  {
    key: 'iba',
    name: 'IBA',
    nameEnglish: 'IBA Admission',
    category: 'business',
    iconType: 'iba',
    color: '#991B1B',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-100',
    totalQuestions: 3900,
    solvedQuestions: 64,
  },
];

export const PRESET_EXAMS_LIST: PresetExamConfig[] = [
  {
    id: 'du_ka',
    name: "ঢাবি 'ক'",
    title: "ঢাবি 'ক' প্রিসেট",
    durationMinutes: 45,
    totalQuestions: 60,
    mandatorySubjects: [
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 15 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 15 },
    ],
    optionalSubjects: [
      { subjectKey: 'bangla', name: 'বাংলা', count: 15 },
      { subjectKey: 'english', name: 'English', count: 15 },
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 15 },
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 15 },
    ],
    requiredOptionalCount: 2,
  },
  {
    id: 'sust_a',
    name: 'SUST A',
    title: 'SUST A ইউনিট প্রিসেট',
    durationMinutes: 50,
    totalQuestions: 60,
    mandatorySubjects: [
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 20 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 20 },
    ],
    optionalSubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 20 },
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 20 },
      { subjectKey: 'english', name: 'English', count: 20 },
    ],
    requiredOptionalCount: 1,
  },
  {
    id: 'du_kha',
    name: "ঢাবি 'খ'",
    title: "ঢাবি 'খ' প্রিসেট",
    durationMinutes: 45,
    totalQuestions: 60,
    mandatorySubjects: [
      { subjectKey: 'bangla', name: 'বাংলা', count: 20 },
      { subjectKey: 'english', name: 'English', count: 20 },
      { subjectKey: 'gk', name: 'সাধারণ জ্ঞান', count: 20 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'ju_a',
    name: 'জাবি এ',
    title: 'জাবি এ ইউনিট প্রিসেট',
    durationMinutes: 55,
    totalQuestions: 80,
    mandatorySubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 22 },
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 22 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 22 },
      { subjectKey: 'bangla', name: 'বাংলা', count: 7 },
      { subjectKey: 'english', name: 'English', count: 7 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'ju_d',
    name: 'জাবি ডি',
    title: 'জাবি ডি ইউনিট প্রিসেট',
    durationMinutes: 55,
    totalQuestions: 80,
    mandatorySubjects: [
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 44 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 24 },
      { subjectKey: 'bangla', name: 'বাংলা ও ইংরেজি', count: 8 },
      { subjectKey: 'gk', name: 'সাধারণ জ্ঞান', count: 4 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'medical',
    name: 'মেডিকেল',
    title: 'মেডিকেল (MBBS) প্রিসেট',
    durationMinutes: 60,
    totalQuestions: 100,
    mandatorySubjects: [
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 30 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 25 },
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 20 },
      { subjectKey: 'english', name: 'English', count: 15 },
      { subjectKey: 'gk', name: 'সাধারণ জ্ঞান', count: 10 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'buet',
    name: 'বুয়েট',
    title: 'বুয়েট প্রাক-নির্বাচনী প্রিসেট',
    durationMinutes: 60,
    totalQuestions: 100,
    mandatorySubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 34 },
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 33 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 33 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
  {
    id: 'cu_a',
    name: 'সিইউ এ',
    title: 'চট্টগ্রাম বিশ্ববিদ্যালয় এ ইউনিট',
    durationMinutes: 60,
    totalQuestions: 100,
    mandatorySubjects: [
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 25 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 25 },
    ],
    optionalSubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 25 },
      { subjectKey: 'biology', name: 'জীববিজ্ঞান', count: 25 },
      { subjectKey: 'english', name: 'English', count: 25 },
    ],
    requiredOptionalCount: 2,
  },
  {
    id: 'ruet',
    name: 'রুয়েট',
    title: 'ইঞ্জিনিয়ারিং গুচ্ছ প্রিসেট',
    durationMinutes: 60,
    totalQuestions: 100,
    mandatorySubjects: [
      { subjectKey: 'math', name: 'উচ্চতর গণিত', count: 35 },
      { subjectKey: 'physics', name: 'পদার্থবিজ্ঞান', count: 35 },
      { subjectKey: 'chemistry', name: 'রসায়ন', count: 30 },
    ],
    optionalSubjects: [],
    requiredOptionalCount: 0,
  },
];

export const SUBJECT_TOPICS_DATABASE: Record<string, PaperNode[]> = {
  chemistry: [
    {
      paper: '1st',
      label: '১ম পত্র',
      totalQuestions: 8100,
      solvedQuestions: 154,
      chapters: [
        {
          id: 'chem1_ch1',
          name: 'ল্যাবরেটরির নিরাপদ ব্যবহার',
          paper: '1st',
          totalQuestions: 520,
          solvedQuestions: 17,
          subtopics: [
            { id: 'c1c1_s1', name: 'T-01: ল্যাবরেটরির নিরাপত্তা সামগ্রী, যন্ত্রপাতি ও সুরক্ষা বিধি', totalQuestions: 180, solvedQuestions: 6 },
            { id: 'c1c1_s2', name: 'T-02: প্রাইমারি ও সেকেন্ডারি স্ট্যান্ডার্ড পদার্থ', totalQuestions: 160, solvedQuestions: 5 },
            { id: 'c1c1_s3', name: 'T-03: হ্যাজার্ড প্রতীক ও রাসায়নিক বর্জ্য ব্যবস্থাপনা', totalQuestions: 180, solvedQuestions: 6 },
          ],
        },
        {
          id: 'chem1_ch2',
          name: 'গুণগত রসায়ন',
          paper: '1st',
          totalQuestions: 2200,
          solvedQuestions: 61,
          subtopics: [
            { id: 'c1c2_s1', name: 'T-01: পরমাণু ও তার মূল কণিকাসমূহ', totalQuestions: 120, solvedQuestions: 6 },
            { id: 'c1c2_s2', name: 'T-02: আইসোটোপ, আইসোটোন, আইসোবার ও আইসোইলেকট্রনিক', totalQuestions: 180, solvedQuestions: 8 },
            { id: 'c1c2_s3', name: 'T-03: পারমাণবিক ভর ও আপেক্ষিক পারমাণবিক ভর সংক্রান্ত', totalQuestions: 60, solvedQuestions: 2 },
            { id: 'c1c2_s4', name: 'T-04: অরবিট, অরবিটাল এবং কোয়ান্টাম সংখ্যা সংক্রান্ত', totalQuestions: 260, solvedQuestions: 10 },
            { id: 'c1c2_s5', name: 'T-05: ইলেকট্রন বিন্যাসের নিয়ম নীতি সংক্রান্ত', totalQuestions: 290, solvedQuestions: 10 },
            { id: 'c1c2_s6', name: 'T-06: কোয়ান্টাম বলবিদ্যা ব্যবহার করে ইলেকট্রনের বিভিন্ন গতীয় রাশি নির্ণয়', totalQuestions: 110, solvedQuestions: 4 },
            { id: 'c1c2_s7', name: 'T-07: বর্ণালি ও রিডবার্গ সমীকরণ সংক্রান্ত সমস্যা', totalQuestions: 310, solvedQuestions: 8 },
            { id: 'c1c2_s8', name: 'T-08: দ্রাব্যতা ও দ্রাব্যতার উপর বিভিন্ন নিয়ামকের প্রভাব', totalQuestions: 240, solvedQuestions: 5 },
            { id: 'c1c2_s9', name: 'T-09: দ্রাব্যতা গুণফল ও আয়নিক গুণফল সংক্রান্ত সমস্যা (Ksp & Kip)', totalQuestions: 280, solvedQuestions: 4 },
            { id: 'c1c2_s10', name: 'T-10: আয়ন শনাক্তকরণ (শিখা পরীক্ষা ও সিক্ত পরীক্ষা)', totalQuestions: 350, solvedQuestions: 4 },
          ],
        },
        {
          id: 'chem1_ch3',
          name: 'মৌলের পর্যায়বৃত্ত ধর্ম ও রাসায়নিক বন্ধন',
          paper: '1st',
          totalQuestions: 2600,
          solvedQuestions: 40,
          subtopics: [
            { id: 'c1c3_s1', name: 'T-01: পর্যায় সারণি ও অবস্থান নির্ণয় সংক্রান্ত', totalQuestions: 180, solvedQuestions: 3 },
            { id: 'c1c3_s2', name: 'T-02: ব্লক মৌলের সাধারণ ধর্ম ও কর্ণ-সম্পর্ক সংক্রান্ত', totalQuestions: 220, solvedQuestions: 4 },
            { id: 'c1c3_s3', name: 'T-03: d-ব্লক মৌল, অবস্থান্তর মৌল, জটিল যৌগের সংকরায়ন ও নামকরণ', totalQuestions: 260, solvedQuestions: 4 },
            { id: 'c1c3_s4', name: 'T-04: পর্যায়বৃত্ত ধর্ম (আকার, IE, EA, EN, গলনাঙ্ক ও স্ফুটনাঙ্ক)', totalQuestions: 380, solvedQuestions: 8 },
            { id: 'c1c3_s5', name: 'T-05: মৌলের অক্সাইড ধর্ম', totalQuestions: 170, solvedQuestions: 3 },
            { id: 'c1c3_s6', name: 'T-06: আয়নিক, সমযোজী, সন্নিবেশ ও ধাতব বন্ধন', totalQuestions: 200, solvedQuestions: 3 },
            { id: 'c1c3_s7', name: 'T-07: অরবিটাল অধিক্রমণ (সিগমা ও পাই বন্ধন)', totalQuestions: 120, solvedQuestions: 2 },
            { id: 'c1c3_s8', name: 'T-08: হাইব্রিডাইজেশন, যৌগের আকৃতি, বন্ধন কোণ ও VSEPR তত্ত্ব', totalQuestions: 460, solvedQuestions: 7 },
            { id: 'c1c3_s9', name: 'T-09: পোলারায়ন, ফাজানের নীতি ও পোলারিটি', totalQuestions: 230, solvedQuestions: 3 },
            { id: 'c1c3_s10', name: 'T-10: হাইড্রোজেন বন্ধন ও ভ্যানডার ওয়ালস বন্ধন', totalQuestions: 240, solvedQuestions: 2 },
            { id: 'c1c3_s11', name: 'T-11: আকরিক, গুরুত্বপূর্ণ যৌগ ও রাসায়নিক সংকেত', totalQuestions: 140, solvedQuestions: 1 },
          ],
        },
        {
          id: 'chem1_ch4',
          name: 'রাসায়নিক পরিবর্তন',
          paper: '1st',
          totalQuestions: 1900,
          solvedQuestions: 11,
          subtopics: [
            { id: 'c1c4_s1', name: 'T-01: রাসায়নিক বিক্রিয়া ও গ্রিন কেমিস্ট্রি', totalQuestions: 120, solvedQuestions: 1 },
            { id: 'c1c4_s2', name: 'T-02: বিক্রিয়ার হার ও হার ধ্রুবক সংক্রান্ত সমস্যা', totalQuestions: 210, solvedQuestions: 1 },
            { id: 'c1c4_s3', name: 'T-03: রাসায়নিক সাম্যাবস্থা, লা-শাতেলিয়ারের নীতি ও ভ্যান্ট হফ সমীকরণ', totalQuestions: 290, solvedQuestions: 2 },
            { id: 'c1c4_s4', name: 'T-04: সাম্যধ্রুবক Kp ও Kc সংক্রান্ত সমস্যা', totalQuestions: 340, solvedQuestions: 2 },
            { id: 'c1c4_s5', name: 'T-05: এসিড ও ক্ষারক (ব্রনস্টেড-লাউরি ও লুইস মতবাদ)', totalQuestions: 200, solvedQuestions: 1 },
            { id: 'c1c4_s6', name: 'T-06: পানির আয়নিক গুণফল (Kw) সংক্রান্ত', totalQuestions: 140, solvedQuestions: 1 },
            { id: 'c1c4_s7', name: 'T-07: এসিড ও ক্ষারকের বিয়োজন ধ্রুবক (Ka, Kb) ও লঘুকরণ সূত্র', totalQuestions: 110, solvedQuestions: 0 },
            { id: 'c1c4_s8', name: 'T-08: pH, pOH ও হাইড্রোজেন আয়ন ঘনমাত্রা সংক্রান্ত সমস্যা', totalQuestions: 310, solvedQuestions: 2 },
            { id: 'c1c4_s9', name: 'T-09: বাফার দ্রবণ সংক্রান্ত সমস্যা (হেন্ডারসন-হ্যাসেলবাল্ক সমীকরণ)', totalQuestions: 180, solvedQuestions: 1 },
          ],
        },
        {
          id: 'chem1_ch5',
          name: 'কর্মমুখী রসায়ন',
          paper: '1st',
          totalQuestions: 821,
          solvedQuestions: 25,
          subtopics: [
            { id: 'c1c5_s1', name: 'T-01: খাদ্য সংরক্ষক (প্রিজারভেটিভস ও অ্যান্টিঅক্সিডেন্ট)', totalQuestions: 380, solvedQuestions: 12 },
            { id: 'c1c5_s2', name: 'T-02: ভিনেগার (মল্ট ভিনেগার ও কার্যকৌশল)', totalQuestions: 241, solvedQuestions: 8 },
            { id: 'c1c5_s3', name: 'T-03: টয়লেট্রিজ, পারফিউমারি ও পরিষ্কারক সামগ্রী', totalQuestions: 200, solvedQuestions: 5 },
          ],
        },
      ],
    },
    {
      paper: '2nd',
      label: '২য় পত্র',
      totalQuestions: 8900,
      solvedQuestions: 44,
      chapters: [
        {
          id: 'chem2_ch1',
          name: 'পরিবেশ রসায়ন',
          paper: '2nd',
          totalQuestions: 1700,
          solvedQuestions: 10,
          subtopics: [
            { id: 'c2_1_1', name: '১.১ বায়ুমণ্ডল এর গঠন, উপাদান', totalQuestions: 110, solvedQuestions: 1 },
            { id: 'c2_1_2', name: '১.২ ঘূর্ণিঝড় ও জলোচ্ছ্বাস', totalQuestions: 11, solvedQuestions: 0 },
            { id: 'c2_1_3', name: 'বয়েল, চার্লস ও অ্যাভোগাড্রো সূত্র এবং আদর্শ গ্যাস সমীকরণ', totalQuestions: 480, solvedQuestions: 4 },
            { id: 'c2_1_4', name: 'ডাল্টনের আংশিক চাপ ও গ্রাহামের ব্যাপন সূত্র', totalQuestions: 390, solvedQuestions: 3 },
            { id: 'c2_1_5', name: 'লুইস এসিড-ক্ষারক ও পানির বিশুদ্ধতার মানদণ্ড (DO, BOD, COD)', totalQuestions: 709, solvedQuestions: 2 },
          ],
        },
        {
          id: 'chem2_ch2',
          name: 'জৈব যৌগ',
          paper: '2nd',
          totalQuestions: 3600,
          solvedQuestions: 20,
          subtopics: [
            { id: 'c2_2_1', name: 'জৈব যৌগের নামকরণ ও সমাণুতা', totalQuestions: 850, solvedQuestions: 6 },
            { id: 'c2_2_2', name: 'অ্যালিফেটিক হাইড্রোকার্বন ও প্রস্তুতি', totalQuestions: 750, solvedQuestions: 4 },
            { id: 'c2_2_3', name: 'অ্যারোমেটিক যৌগ ও ইলেক্ট্রোফিলিক প্রতিস্থাপন', totalQuestions: 980, solvedQuestions: 5 },
            { id: 'c2_2_4', name: 'অ্যালকোহল, অ্যালডিহাইড, কিটোন ও অ্যাসিড', totalQuestions: 1020, solvedQuestions: 5 },
          ],
        },
        {
          id: 'chem2_ch3',
          name: 'পরিমাণগত রসায়ন',
          paper: '2nd',
          totalQuestions: 1700,
          solvedQuestions: 12,
          subtopics: [
            { id: 'c2_3_1', name: 'মোলারিটি, শতকরা মাত্রা ও দ্রবণের ঘনমাত্রা', totalQuestions: 520, solvedQuestions: 5 },
            { id: 'c2_3_2', name: 'এসিড-ক্ষার টাইট্রেশন ও নির্দেশক', totalQuestions: 640, solvedQuestions: 4 },
            { id: 'c2_3_3', name: 'জারণ-বিজারণ সমতাকরণ ও আয়োডিমিতি', totalQuestions: 540, solvedQuestions: 3 },
          ],
        },
        {
          id: 'chem2_ch4',
          name: 'তড়িৎ রসায়ন',
          paper: '2nd',
          totalQuestions: 1200,
          solvedQuestions: 2,
          subtopics: [
            { id: 'c2_4_1', name: 'তড়িৎ পরিবাহী ও ফ্যারাডের সূত্র', totalQuestions: 450, solvedQuestions: 1 },
            { id: 'c2_4_2', name: 'তড়িৎ রাসায়নিক কোষ ও নার্নস্ট সমীকরণ', totalQuestions: 750, solvedQuestions: 1 },
          ],
        },
      ],
    },
  ],
  physics: [
    {
      paper: '1st',
      label: '১ম পত্র',
      totalQuestions: 4800,
      solvedQuestions: 160,
      chapters: [
        {
          id: 'phy1_ch1',
          name: 'ভৌতজগত ও পরিমাপ',
          paper: '1st',
          totalQuestions: 520,
          solvedQuestions: 25,
          subtopics: [
            { id: 'p1_1_1', name: 'ভৌত রাশি, একক ও মাত্রা সমীকরণ', totalQuestions: 220, solvedQuestions: 15 },
            { id: 'p1_1_2', name: 'ভার্নিয়ার স্কেল, স্লাইড ক্যালিপার্স ও স্ক্রু গজ', totalQuestions: 180, solvedQuestions: 6 },
            { id: 'p1_1_3', name: 'পরিমাপের ত্রুটি ও শতকরা ত্রুটি হিসাব', totalQuestions: 120, solvedQuestions: 4 },
          ],
        },
        {
          id: 'phy1_ch2',
          name: 'ভেক্টর',
          paper: '1st',
          totalQuestions: 1450,
          solvedQuestions: 50,
          subtopics: [
            { id: 'p1_2_1', name: 'ভেক্টর যোজন, সামান্তরিক সূত্র ও লব্ধি', totalQuestions: 450, solvedQuestions: 18 },
            { id: 'p1_2_2', name: 'স্কেলার ও ভেক্টর গুণন (ডট ও ক্রস গুণন)', totalQuestions: 520, solvedQuestions: 16 },
            { id: 'p1_2_3', name: 'নদী-নৌকা ও বৃষ্টির ছাতা সমস্যা', totalQuestions: 480, solvedQuestions: 16 },
          ],
        },
        {
          id: 'phy1_ch3',
          name: 'গতিবিদ্যা',
          paper: '1st',
          totalQuestions: 1100,
          solvedQuestions: 45,
          subtopics: [
            { id: 'p1_3_1', name: '১-মাত্রিক গতি ও সমীকরণ', totalQuestions: 420, solvedQuestions: 20 },
            { id: 'p1_3_2', name: 'প্রাসের গতি (তির্যক ও অনুভূমিক প্রক্ষেপক)', totalQuestions: 680, solvedQuestions: 25 },
          ],
        },
        {
          id: 'phy1_ch4',
          name: 'নিউটনিয়ান বলবিদ্যা',
          paper: '1st',
          totalQuestions: 1730,
          solvedQuestions: 40,
          subtopics: [
            { id: 'p1_4_1', name: 'নিউটনের গতিসূত্র, ভরবেগ ও বলের ঘাত', totalQuestions: 480, solvedQuestions: 12 },
            { id: 'p1_4_2', name: 'ঘর্ষণ ও বৃত্তাকার গতি এবং রাস্তার ব্যাংকিং', totalQuestions: 650, solvedQuestions: 15 },
            { id: 'p1_4_3', name: 'জড়তার ভ্রামক ও চক্রগতির ব্যাসার্ধ', totalQuestions: 600, solvedQuestions: 13 },
          ],
        },
      ],
    },
    {
      paper: '2nd',
      label: '২য় পত্র',
      totalQuestions: 4700,
      solvedQuestions: 160,
      chapters: [
        {
          id: 'phy2_ch1',
          name: 'তাপগতিবিদ্যা',
          paper: '2nd',
          totalQuestions: 1400,
          solvedQuestions: 60,
          subtopics: [
            { id: 'p2_1_1', name: 'তাপগতিবিদ্যার ১ম সূত্র ও রুদ্ধতাপীয় প্রক্রিয়া', totalQuestions: 520, solvedQuestions: 25 },
            { id: 'p2_1_2', name: 'কার্নো চক্র, কর্মদক্ষতা ও এনট্রপি', totalQuestions: 880, solvedQuestions: 35 },
          ],
        },
        {
          id: 'phy2_ch2',
          name: 'স্থির তড়িৎ',
          paper: '2nd',
          totalQuestions: 1600,
          solvedQuestions: 50,
          subtopics: [
            { id: 'p2_2_1', name: 'কুলম্বের সূত্র ও তড়িৎ প্রাবল্য/বিভব', totalQuestions: 750, solvedQuestions: 25 },
            { id: 'p2_2_2', name: 'ধারক ও ধারকত্ব এবং শক্তির হিসাব', totalQuestions: 850, solvedQuestions: 25 },
          ],
        },
        {
          id: 'phy2_ch3',
          name: 'চল তড়িৎ',
          paper: '2nd',
          totalQuestions: 1700,
          solvedQuestions: 50,
          subtopics: [
            { id: 'p2_3_1', name: 'ওহমের সূত্র, রোধের সূত্র ও তুল্য রোধ', totalQuestions: 680, solvedQuestions: 22 },
            { id: 'p2_3_2', name: 'কার্শফের সূত্র ও হুইটস্টোন ব্রিজ', totalQuestions: 1020, solvedQuestions: 28 },
          ],
        },
      ],
    },
  ],
  math: [
    {
      paper: '1st',
      label: '১ম পত্র',
      totalQuestions: 4600,
      solvedQuestions: 120,
      chapters: [
        {
          id: 'm1_ch1',
          name: 'ম্যাট্রিক্স ও নির্ণায়ক',
          paper: '1st',
          totalQuestions: 980,
          solvedQuestions: 40,
          subtopics: [
            { id: 'm1_1_1', name: 'ম্যাট্রিক্সের প্রকারভেদ ও গুণন', totalQuestions: 480, solvedQuestions: 20 },
            { id: 'm1_1_2', name: 'নির্ণায়কের ধর্মাবলি ও ক্রেমারের নিয়ম', totalQuestions: 500, solvedQuestions: 20 },
          ],
        },
        {
          id: 'm1_ch3',
          name: 'সরলরেখা',
          paper: '1st',
          totalQuestions: 1600,
          solvedQuestions: 45,
          subtopics: [
            { id: 'm1_3_1', name: 'বিন্দু, দূরত্ব ও কার্তেসীয়-পোলার স্থানাঙ্ক', totalQuestions: 600, solvedQuestions: 20 },
            { id: 'm1_3_2', name: 'সরলরেখার সমীকরণ, ঢাল ও লম্ব দূরত্ব', totalQuestions: 1000, solvedQuestions: 25 },
          ],
        },
        {
          id: 'm1_ch9',
          name: 'অন্তরীকরণ (Calculus)',
          paper: '1st',
          totalQuestions: 2020,
          solvedQuestions: 35,
          subtopics: [
            { id: 'm1_9_1', name: 'সীমা (Limit) ও মূল নিয়মে অন্তরীকরণ', totalQuestions: 620, solvedQuestions: 12 },
            { id: 'm1_9_2', name: 'পর্যায়ক্রমিক অন্তরজ ও গুরুমান-লঘুমান', totalQuestions: 1400, solvedQuestions: 23 },
          ],
        },
      ],
    },
    {
      paper: '2nd',
      label: '২য় পত্র',
      totalQuestions: 4500,
      solvedQuestions: 120,
      chapters: [
        {
          id: 'm2_ch3',
          name: 'জটিল সংখ্যা',
          paper: '2nd',
          totalQuestions: 1200,
          solvedQuestions: 40,
          subtopics: [
            { id: 'm2_3_1', name: 'মডুলাস, আর্গুমেন্ট ও সঞ্চারপথ', totalQuestions: 600, solvedQuestions: 20 },
            { id: 'm2_3_2', name: 'এককের ঘনমূল ও জটিল রাশির বর্গমূল', totalQuestions: 600, solvedQuestions: 20 },
          ],
        },
        {
          id: 'm2_ch4',
          name: 'বহুপদী ও বহুপদী সমীকরণ',
          paper: '2nd',
          totalQuestions: 1500,
          solvedQuestions: 40,
          subtopics: [
            { id: 'm2_4_1', name: 'দ্বিঘাত সমীকরণের মূলের প্রকৃতি ও নিশ্চায়ক', totalQuestions: 800, solvedQuestions: 20 },
            { id: 'm2_4_2', name: 'ত্রিঘাত সমীকরণ ও সাধারণ মূল শর্ত', totalQuestions: 700, solvedQuestions: 20 },
          ],
        },
        {
          id: 'm2_ch6',
          name: 'কণিক (Conics)',
          paper: '2nd',
          totalQuestions: 1800,
          solvedQuestions: 40,
          subtopics: [
            { id: 'm2_6_1', name: 'পরাবৃত্ত (Parabola)', totalQuestions: 700, solvedQuestions: 18 },
            { id: 'm2_6_2', name: 'উপবৃত্ত ও অধিবৃত্ত (Ellipse & Hyperbola)', totalQuestions: 1100, solvedQuestions: 22 },
          ],
        },
      ],
    },
  ],
  biology: [
    {
      paper: '1st',
      label: '১ম পত্র (উদ্ভিদবিজ্ঞান)',
      totalQuestions: 4200,
      solvedQuestions: 90,
      chapters: [
        {
          id: 'bio1_ch1',
          name: 'কোষ ও এর গঠন',
          paper: '1st',
          totalQuestions: 1200,
          solvedQuestions: 35,
          subtopics: [
            { id: 'b1_1_1', name: 'কোষ প্রাচীর, প্লাজমামেমব্রেন ও অঙ্গাণু', totalQuestions: 600, solvedQuestions: 20 },
            { id: 'b1_1_2', name: 'DNA, RNA ও প্রোটিন সংশ্লেষ (Central Dogma)', totalQuestions: 600, solvedQuestions: 15 },
          ],
        },
        {
          id: 'bio1_ch2',
          name: 'কোষ বিভাজন',
          paper: '1st',
          totalQuestions: 1100,
          solvedQuestions: 30,
          subtopics: [
            { id: 'b1_2_1', name: 'মাইটোটিক কোষ বিভাজন ও পর্যায়সমূহ', totalQuestions: 550, solvedQuestions: 15 },
            { id: 'b1_2_2', name: 'মিয়োসিস ও ক্রসিং ওভার', totalQuestions: 550, solvedQuestions: 15 },
          ],
        },
        {
          id: 'bio1_ch8',
          name: 'টিস্যু ও টিস্যুতন্ত্র',
          paper: '1st',
          totalQuestions: 1900,
          solvedQuestions: 25,
          subtopics: [
            { id: 'b1_8_1', name: 'ভাজক টিস্যু ও প্রকারভেদ', totalQuestions: 900, solvedQuestions: 12 },
            { id: 'b1_8_2', name: 'ভাস্কুলার বান্ডল ও অন্তর্গঠন', totalQuestions: 1000, solvedQuestions: 13 },
          ],
        },
      ],
    },
    {
      paper: '2nd',
      label: '২য় পত্র (প্রাণিবিজ্ঞান)',
      totalQuestions: 4000,
      solvedQuestions: 90,
      chapters: [
        {
          id: 'bio2_ch1',
          name: 'প্রাণীর বিভিন্নতা ও শ্রেণিবিন্যাস',
          paper: '2nd',
          totalQuestions: 1400,
          solvedQuestions: 35,
          subtopics: [
            { id: 'b2_1_1', name: 'শ্রেণিবিন্যাসের ভিত্তি ও প্রধান ৯টি পর্ব', totalQuestions: 800, solvedQuestions: 20 },
            { id: 'b2_1_2', name: 'কর্ডাটার উপপর্ব ও শ্রেণির বৈশিষ্ট্য', totalQuestions: 600, solvedQuestions: 15 },
          ],
        },
        {
          id: 'bio2_ch3',
          name: 'মানব শারীরতত্ত্ব: পরিপাক ও শোষণ',
          paper: '2nd',
          totalQuestions: 1500,
          solvedQuestions: 30,
          subtopics: [
            { id: 'b2_3_1', name: 'মুখগহ্বর, পাকস্থলী ও অন্ত্রে পরিপাক', totalQuestions: 750, solvedQuestions: 15 },
            { id: 'b2_3_2', name: 'যকৃত, অগ্ন্যাশয় ও পরিপাকে হরমোন-এনজাইম', totalQuestions: 750, solvedQuestions: 15 },
          ],
        },
        {
          id: 'bio2_ch4',
          name: 'মানব শারীরতত্ত্ব: রক্ত ও সংবহন',
          paper: '2nd',
          totalQuestions: 1100,
          solvedQuestions: 25,
          subtopics: [
            { id: 'b2_4_1', name: 'রক্তরস, রক্তকণিকা ও রক্ত তঞ্চন', totalQuestions: 550, solvedQuestions: 12 },
            { id: 'b2_4_2', name: 'হৃৎপিণ্ডের গঠন, কার্ডিয়াক চক্র ও রক্তচাপ', totalQuestions: 550, solvedQuestions: 13 },
          ],
        },
      ],
    },
  ],
};
